name: linux-delve64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: go run _scripts/make.go build
    - uses: actions/upload-artifact@v4
      with:
        name: linux-delve64
        path: dlv
        if-no-files-found: error
