name: mac-delve-aarch64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: install go
      run: brew install go
    - name: build
      run: go run _scripts/make.go build
    - uses: actions/upload-artifact@v4
      with:
        name: mac-delve-aarch64
        path: dlv
        if-no-files-found: error
