name: windows-netcoredbg64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: go run _scripts/make.go build
    - uses: actions/upload-artifact@v4
      with:
        name: windows-netcoredbg64
        path: dlv.exe
        if-no-files-found: error
